### ISSUE TITLE
Wersja beta

### ISSUE THREAD

**Issue by robertkandzia** [DrupalCampWroclaw/androidapp_2015#2]
Jak by ktoś chciał przetestować i skomentować to przesyłam plik instalacyjny :smirk: 

Link do pobrania: ~~[drupalcamp_2015_app-beta1.apk](http://pro.robbo.eu/drupalcamp_2015_mobile/app/drupalcamp_2015_app-beta1.apk)~~

Jeśli wszystko będzie OK, to w poniedziałek apka zostanie opublikowana na https://play.google.com.

**Comment by grzegorzbartman** [comment]
Przetestowałem. Wszystko działa OK. Możemy to jutro opublikować.

PR: https://github.com/DrupalCampWroclaw/androidapp_2015/pull/3

**Comment by robertkandzia** [comment]
@grzegorzbartman Dzięki.

Wersja po dodaniu nowej funkcjonalności #4. Nie trzeba testować.
Link do pobrania: [drupalcamp_2015_app-beta2.apk](http://pro.robbo.eu/drupalcamp_2015_mobile/app/drupalcamp_2015_app-beta2.apk)

**Comment by grzegorzbartman** [comment]
"Aplikacja czeka na publikację. Może minąć kilka godzin, zanim zostanie udostępniona w Google Play."

**Comment by robertkandzia** [comment]
Jest :-) https://play.google.com/store/apps/details?id=pl.drupalcampwroclaw.drupalcamp2015
