### ISSUE TITLE
Aplikacja mobilna 2016

### ISSUE THREAD

**Issue by robertkandzia** [DrupalCampWroclaw/androidapp_2015#5]
Jak by ktoś chciał przetestować apke przed aktualizacją na Google Play :smirk: 

Zaktualizowana apka z ubiegłego roku.
Link do pobrania: [drupalcamp_2016_app-beta1.apk](http://pro.robbo.eu/drupalcamp_2015_mobile/app/drupalcamp_2016_app-beta1.apk)

**Comment by grzegorzbartman** [comment]
U mnie wszystko działa

**Comment by robertkandzia** [comment]
Super. Z publikacją zaczekamy do końca tygodnia. Pewnie dojdzie logo sponsora.

**Comment by robertkandzia** [comment]
@grzegorzbartman możesz zaaktualizować apke w wersji beta-1 na Google Play?
